base:
  image: ubuntu:14.04
  working_dir: /srv
  volumes:
    - .:/srv

npm:
  extends: {'service': 'base'}
  image: library/node
  command: /bin/bash -c 'umask 0000 && npm install'

sass:
  extends: {'service': 'base'}
  image: ubuntudesign/sass
  command: /bin/bash -c 'umask 0000 && sass --debug-info --update static/css --force -E "UTF-8"'

web:
  extends: {'service': 'base'}
  build: .
  ports:
    - "8001:5000"

sass-watch:
  extends: {'service': 'sass'}
  command: /bin/bash -c 'umask 0000 && sass --debug-info --watch static/css -E "UTF-8"'
