version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:v1.6.7

jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt
      - run:
          name: Build the site resources
          command: yarn run build
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 3 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  linkchecker:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Linkchecker
          command: apt-get install -y linkchecker
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Start development server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Wait for development server
          command: sleep 5
      - run:
          name: Run Linkchecker
          command: linkchecker --threads 2 --ignore-url /usn --ignore-url /search --ignore-url ".*(?:png|jpg|jpeg|gif|bmp|svg|js)$" --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /h_* --ignore-url /blog --ignore-url /server/docs --no-warnings http://127.0.0.1
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn lint-python
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
  test-js:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test JS
          command: yarn test-js
workflows:
  version: 2
  build:
    jobs:
      - test-site
      - linkchecker
      - lint-scss
      - lint-python
      - test-python
      - test-js
