name: docs links on ubuntu.com/ceph/docs

on: pull_request

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker --threads 2 --ignore-url "https://www.gstatic.com" --ignore-url "https://assets.ubuntu.com$" --check-extern --no-warnings https://ubuntu.com/ceph/docs

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=docs
