name: docs links on ubuntu.com/core/docs

on:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: |
          linkchecker --no-follow-url '!https:\/\/ubuntu.com\/core\/docs' \
          	--ignore-url https://res.cloudinary.com \
          	--ignore-url q_auto \
          	--ignore-url fl_sanitize \
          	--ignore-url c_fill \
          	--ignore-url e_sharpen \
          	--ignore-url w_[0-9]* \
          	--ignore-url h_[0-9]* \
            --check-extern \
            --no-status \
            --timeout 1000 \
            --no-warnings https://ubuntu.com/core/docs

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=docs
