name: Cypress checks / forms
env:
  SECRET_KEY: insecure_test_key
  PORT: 8001
  CONTRACTS_API_URL: https://contracts.staging.canonical.com
  STRIPE_PUBLISHABLE_KEY: pk_test_yndN9H0GcJffPe0W58Nm64cM00riYG4N46
  CAPTCHA_TESTING_API_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  MARKETO_API_CLIENT: ${{secrets.MARKETO_API_CLIENT}}
  MARKETO_API_SECRET: ${{secrets.MARKETO_API_SECRET}}
  DISCOURSE_API_KEY: ${{secrets.DISCOURSE_API_KEY}}
  DISCOURSE_API_USERNAME: ${{secrets.DISCOURSE_API_USERNAME}}

on:
  schedule:
    - cron: "0 14 * * 1-5"
      branches:
        - main

jobs:
  run-cypress:
    if: github.repository == 'canonical/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run serve
          wait-on: "http://0.0.0.0:8001/_status/check"
          wait-on-timeout: 360
          browser: chrome
          config-file: tests/cypress/cypress.json
          config: baseUrl=http://0.0.0.0:8001,integrationFolder=tests/cypress/forms

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web--design
