name: Links in master

on:
  schedule:
    - cron: "10 7 * * *"

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pw

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag ubuntu-com .

      - name: Run the server
        run: docker run --detach --publish 80:80 --env SECRET_KEY=insecure_secret_key --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres ubuntu-com

      - name: Install linkchecker
        run: sudo apt update && sudo apt install linkchecker

      - name: Run linkchecker
        run: linkchecker --threads 0 --timeout 120 --ignore-url /search --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /h_* --ignore-url /blog --ignore-url /server/docs --no-warnings http://127.0.0.1

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=%23web-team
