name: Links in master

on:
  schedule:
    - cron: "0 8 * * 1-5"

jobs:
  check-links:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pw

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag ubuntu-com .

      - name: Run the server
        run: docker run --detach --publish 80:80 --env SECRET_KEY=insecure_secret_key --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres ubuntu-com

      - name: Install linkchecker
        # As soon as version 10 is released we should replace this:
        run: pip3 install git+https://github.com/linkchecker/linkchecker.git

      - name: Run linkchecker
        run: linkchecker --threads 0 --timeout 120 --ignore-url /search --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /h_* --ignore-url /blog --ignore-url /server/docs --no-warnings http://127.0.0.1
