name: docs links on docs.openstack.org/charm-guide/latest/

on:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: |
          linkchecker --no-follow-url '!https:\/\/docs.openstack.org\/charm-guide\/latest\/' \
            --ignore-url http://localhost:8001\* \
            --ignore-url https://groups.openstack.org \
            --ignore-url https://openstack.org/projects/ \
            --ignore-url https://openstack.org/projects/openstack-faq/ \
            --ignore-url ^.*\.css \
            --check-extern \
            --no-status \
            --timeout 1000 \
            --no-warnings https://docs.openstack.org/charm-guide/latest/

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=docs
