name: Generate sitemap for static pages on ubuntu.com
on:
  push:
    branches:
      - main
    paths:
      - "templates/**"

jobs:
  generate-sitemap:
    if: github.repository == 'canonical/ubuntu.com'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Call sitemap generation endpoint
        env:
          SITEMAP_SECRET: ${{ secrets.SITEMAP_SECRET }}
        run: |
          curl --fail-with-body -X POST "https://ubuntu.com/sitemap_tree.xml" \
          -H "Authorization: Bearer $SITEMAP_SECRET"

      - name: Send message on failure
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" $BOT_URL?room=web-alerts
