name: Generate sitemap for static pages
on: [pull_request]
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "templates/**"

jobs:
  generate-sitemap:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call sitemap generation endpoint
        run: |
          curl -f -X POST "https://ubuntu.com/sitemap_tree.xml" \
          -H "Authorization: Bearer invalid-secret-for-qa"